### ISSUE TITLE
Test output formatters

### ISSUE THREAD

**Issue by gerhard** [progrium/basht#2]
I have a test suite which is approaching 100 tests and the output is getting a bit unwieldy. An rspec style progress formatter would be ideal. I wouldn't mind taking a stab at it, was just wondering if you have any thoughts or pointers?

**Comment by progrium** [comment]
Open to it. Just try and keep it as simple as possible. And consult https://github.com/progrium/bashstyle

Thanks!

**Comment by gerhard** [comment]
:+1:

**Comment by gerhard** [comment]
Closing since I haven't made any progress on this, no point in leaving it open.
